[workspace]
authors = ["Tom Mariani <tom.mariani.dev@gmail.com>"]
channels = ["conda-forge"]
name = "gpt"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
train = "python train.py"

[dependencies]
numpy = ">=2.3.3,<3"
pytorch = ">=2.8.0,<3"
ipykernel = ">=6.30.1,<7"
torchinfo = ">=1.8.0,<2"
matplotlib = ">=3.10.6,<4"
pyyaml = ">=6.0.3,<7"
python-box = ">=7.3.2,<8"
